### ISSUE TITLE
Autorun

### ISSUE THREAD

**Issue by ghost** [kosshishub/BetterCustomCSS-BD-plugin#1] opened 2018-02-09 22:33 UTC
Hi,

I have to apply the plugin's settings everytime I run Discord, in order to load the CSS for the first time. Is it possible to automate that please ?

Thanks !

**Comment by kosshi-net** [comment] 2018-02-09 23:11
It is supposed to do exactly that, and it does still work for me. 

Restart, go to the console and paste ``document.querySelector("#bettercustomcss").innerHTML``, if it returns your custom css, the plugin is working correctly and the issue is somewhere else. Maybe it is down to load order? Do you use themes?
You can try delaying the auto apply by replacing line 29 in the source code with 
``setTimeout( ()=> this.appendFile(), 5000 );``

**Comment by ghost** [comment] 2018-02-10 12:04
Actually, the custom CSS is loaded !

But it's just this one which doesn't apply :
```
:root {
    --tm-messages-opacity: 0.2;
}
```

Thanks

**Comment by kosshi-net** [comment] 2018-02-10 14:18
Try ``--tm-messages-opacity: 0.2 !important;`` or that delaying trick. CSS is tricky like this sometimes.

I'll close the issue since the problem is not in the plugin. Tho, if that delaying trick works, I may add it as an optional feature (also, does your CSS work as a BD Theme when starting discord?).

**Closed as completed by kosshi-net** 2018-02-10 14:18 UTC

**Comment by ghost** [comment] 2018-02-10 14:35
The `!important` doesn't change anything, and neither as the delay : I still have to re-apply the CSS in settings.

I use [Beard's Material Theme](http://www.beard-design.com/discord-material-theme/).

Thanks

**Comment by kosshi-net** [comment] 2018-02-10 14:44
That is odd. If you resave the file to trigger it to auto-append, does it work?

**Comment by ghost** [comment] 2018-02-10 16:29
Yes, but the `--tm-messages-opacity` property still doesn't apply.

**Comment by kosshi-net** [comment] 2018-02-10 16:43
That's exactly what I was looking for. Applying settings removes the style element and then adds it back, while auto-apply just edits its contents. Looks like that doesn't change the priority of the css rules.

Replace the whole start function with this:
```
BetterCustomCSS.prototype.start = function () {
	let settings = this.loadSettings();
	let fs = require('fs');
	if(this.accessSync(settings.direcotry)){
		setTimeout( ()=> {
			let elem = document.createElement("style");
			elem.id = "bettercustomcss";
			document.head.appendChild(elem);
			this.watcher = fs.watch(settings.direcotry, {}, this.appendFile.bind(this));
			this.appendFile();
		}, 10000 );
	}
};
```

Adds a 10sec delay to the whole thing.

**Comment by ghost** [comment] 2018-02-11 11:43
It's working, thanks !
